export type Faq = { q: string; a: string };
export type Service = {
  slug: string;
  name: string;
  group: "striping" | "protection" | "repair";
  short: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  kicker: string;
  lead: string;
  hero: string;
  icon: string;
  gallery: string[];
  intro: string[];
  includes: { t: string; d: string }[];
  signs: { title: string; items: string[] };
  process: { t: string; d: string }[];
  faqs: Faq[];
  related: string[];
  posts: string[];
  schemaType: string;
};

export const services: Service[] = [
  {
    slug: "line-striping-service-lancaster-pa",
    name: "Line Striping",
    group: "striping",
    short: "Parking stalls, arrows, stop bars, curbs, crosswalks and stencils for commercial properties across Lancaster County.",
    metaTitle: "Line Striping Service in Lancaster, PA | Lines & Asphalt",
    metaDescription:
      "Line striping in Lancaster, PA for parking lots, roads, loading zones and ADA spaces. Crisp, code-aware pavement markings. Free estimates, call 717-808-1600.",
    h1: "Line striping service in Lancaster, PA",
    kicker: "Pavement markings",
    lead: "Straight lines, correct dimensions, and paint that stays visible. We stripe new layouts and re-stripe worn ones for businesses, churches, schools, apartment communities and industrial sites.",
    hero: "retail-lot-fresh-yellow-stripes",
    icon: "striper",
    gallery: ["shopping-center-yellow-hatching", "retail-lot-angled-yellow-stripes", "white-directional-arrows-lane-line", "lot-arrows-white-center-line", "reserved-stencil-night", "order-here-stencil-drive"],
    intro: [
      "Pavement markings do a quiet job. They tell drivers where to go, tell pedestrians where it is safe to cross, keep fire lanes open, and make a lot hold the number of cars it was designed to hold. When the paint fades, people start parking wherever they like, ADA stalls lose their legal markings, and the property starts to look neglected even when everything else is in good shape.",
      "Line striping is the finishing step of almost every asphalt project, so we handle it as a trade of its own and not as an afterthought. We lay out from measurements, snap chalk lines, and paint with a machine that holds a consistent width. Stencils are placed by hand so letters and symbols sit square in the stall.",
      "We work on small lots and large ones. A church with twenty stalls gets the same attention to layout as a plaza with two hundred. If the existing layout is wrong, we will say so and show you what a better one looks like before any paint goes down.",
    ],
    includes: [
      { t: "Standard and angled stalls", d: "Single and double lines, compact stalls, angled parking and end caps, laid out from measurements." },
      { t: "Arrows, stop bars and crosswalks", d: "Directional arrows, stop bars, yield lines, crosswalks and walkway markings that move traffic the right way." },
      { t: "Stencils", d: "Reserved, visitor, no parking, loading zone, EV, numbered stalls and custom wording." },
      { t: "ADA stalls and aisles", d: "Accessible stalls, access aisle hatching and the symbol of access, spaced and sized correctly." },
      { t: "Curbs and fire lanes", d: "Painted curbs and fire lane markings built to your municipality or fire marshal." },
      { t: "Blackout of old lines", d: "When a layout changes, we cover the old lines so drivers do not follow ghost markings." },
    ],
    signs: {
      title: "Signs your lot needs lines",
      items: [
        "You cannot see the stall lines from fifty feet away.",
        "Customers park across two stalls, or on the aisle, because the lines are gone.",
        "ADA markings are faded, missing, or were never added.",
        "You changed the layout and the old lines still show through.",
        "The lot was just sealcoated, patched or repaved and needs fresh markings.",
        "An insurance or fire inspection flagged missing markings.",
      ],
    },
    process: [
      { t: "Site visit", d: "We walk the lot, look at the existing layout, and measure. You get a written quote after the visit." },
      { t: "Layout", d: "We confirm stall counts, aisle widths and ADA requirements, and mark the plan with chalk lines." },
      { t: "Paint", d: "Lines go down with a striping machine for consistent width. Stencils and symbols are placed by hand." },
      { t: "Dry and reopen", d: "Traffic paint dries quickly. We use cones until it is safe to drive on and reopen the lot the same day." },
    ],
    faqs: [
      { q: "How is line striping priced?", a: "By the size of the lot and what goes on it: the number of stalls, whether the layout is new or a re-stripe, and how many stencils, ADA symbols and arrows are needed. We give a free written quote after seeing the lot or photos of it." },
      { q: "How long does striping take to dry?", a: "Traffic paint is typically dry to the touch within an hour in normal conditions, above about 50 degrees F and without rain. We keep the area coned off until it is safe, and most lots reopen the same day." },
      { q: "Can you stripe at night or on a weekend?", a: "Yes. A lot of our commercial work is scheduled early in the morning, in the evening, or on weekends so that customers and staff are not disrupted." },
      { q: "Do I need to sealcoat before striping?", a: "If the lot is due for sealcoating, do that first. Fresh sealcoat needs to cure before it gets painted, usually 24 to 48 hours. We coordinate both so the lot goes from sealed to striped without a long gap." },
      { q: "How often should a parking lot be re-striped?", a: "Most commercial lots look best with fresh lines every one to two years. High traffic lots such as retail, medical offices and churches with weekly crowds often need yearly touch ups." },
    ],
    related: ["parking-lot-striping-lancaster-pa", "ada-parking-lot-striping-lancaster-pa", "fire-lane-marking-lancaster-pa", "sealcoating-lancaster-pa"],
    posts: ["parking-lot-line-painting-guide", "how-we-stripe-a-parking-lot", "parking-lot-striping-cost", "parking-lot-striping-mistakes"],
    schemaType: "Line striping",
  },
  {
    slug: "parking-lot-striping-lancaster-pa",
    name: "Parking Lot Striping",
    group: "striping",
    short: "Re-striping and new layouts for retail, office, church, school and apartment lots, with ADA and fire lane markings.",
    metaTitle: "Parking Lot Striping & Line Painting in Lancaster, PA",
    metaDescription:
      "Parking lot striping in Lancaster, PA: re-striping, new layouts, ADA stalls, fire lanes and stencils for commercial lots. Free estimates, 717-808-1600.",
    h1: "Parking lot striping and line painting in Lancaster, PA",
    kicker: "Commercial lots",
    lead: "Fresh stall lines, clear aisles and ADA markings that pass inspection. We stripe parking lots for property managers, business owners, congregations and HOAs across Lancaster County.",
    hero: "shopping-center-yellow-hatching",
    icon: "lot",
    gallery: ["retail-lot-yellow-stalls-ada-curb", "retail-lot-restriped-blue-ada", "church-lot-ada-hatched-stalls", "empty-lot-night-white-stalls", "small-business-lot-numbered-stalls", "rear-lot-restriped-numbered"],
    intro: [
      "A parking lot is the first thing a customer touches. If the stalls are faded and the aisles are unclear, it sets the tone before they ever reach your door. If the lines are sharp, the lot looks cared for and the property looks managed.",
      "Most of our parking lot work is a re-stripe: the layout is fine and the paint needs to be renewed. Sometimes the layout itself has to change, because a business added a loading zone, an ADA stall was missing, or the old stall angles waste space. In those cases we measure the lot and plan the new layout before we paint, so the count of stalls and the aisle widths work.",
      "We often work at night for retail and restaurant lots, and early in the morning for offices and medical buildings. The goal is simple: the lot looks great and your customers never notice we were there.",
    ],
    includes: [
      { t: "Re-striping", d: "Painting over existing lines, with a layout check so we do not repeat an old mistake." },
      { t: "New layouts", d: "Measured, chalked and painted for new lots, expansions and reconfigurations." },
      { t: "ADA compliance", d: "Correct counts, sizes, access aisles and symbols, based on your total stall count." },
      { t: "Fire lanes and loading zones", d: "Curb painting and stencils for fire lanes, loading zones and no parking areas." },
      { t: "Traffic flow", d: "Arrows, stop bars, crosswalks and center lines in drive aisles and entrances." },
      { t: "Numbered and reserved stalls", d: "Numbers, reserved stencils, visitor and staff wording, EV stalls." },
    ],
    signs: {
      title: "When to re-stripe or repaint your parking lot lines",
      items: [
        "Lines have worn through to the asphalt in the wheel paths.",
        "Stalls look uneven because earlier crews painted by eye.",
        "You added or lost spaces and the old layout no longer matches.",
        "ADA stalls do not match your total stall count.",
        "You are about to sell, lease or insure the property.",
        "Tenants or customers have complained about parking confusion.",
      ],
    },
    process: [
      { t: "Walk the lot", d: "We measure, count stalls, check existing markings and talk through timing so your business is not interrupted." },
      { t: "Plan the layout", d: "We confirm ADA counts and aisle widths, and flag anything that needs your decision before painting." },
      { t: "Chalk and cone", d: "Every line is snapped and every stall is verified. The work area is coned." },
      { t: "Stripe and stencil", d: "Machine for the lines, hand placement for stencils and symbols, then a final walk with you." },
    ],
    faqs: [
      { q: "How often should I re-stripe my parking lot?", a: "Every one to two years for most commercial lots. If you cannot clearly see the lines from fifty feet away, it is time." },
      { q: "Can you re-stripe without closing my business?", a: "Usually yes. We work in sections, or schedule early mornings, evenings and weekends. Paint dries fast and the lot reopens the same day." },
      { q: "Do you paint over old lines or remove them first?", a: "If the layout stays the same, we paint over the existing lines. If it changes, we black out the old lines so drivers are not following the wrong markings." },
      { q: "Do you handle ADA stalls and signage?", a: "We handle the pavement markings, stall sizes and access aisles. Signs are separate, and we will tell you what the sign has to say and how high it has to be mounted so your contractor or sign company can finish the job." },
      { q: "Is a new layout more work than a re-stripe?", a: "Yes. A re-stripe follows lines that are already there. A new layout means measuring the lot, planning stall counts and ADA stalls, and snapping chalk for every line before painting." },
      { q: "My lot is small. Is it worth calling?", a: "Yes. Small lots are welcome. Bundling striping with crack filling or sealcoating in the same visit makes the most of the trip." },
    ],
    related: ["ada-parking-lot-striping-lancaster-pa", "fire-lane-marking-lancaster-pa", "sealcoating-lancaster-pa", "parking-lot-maintenance-lancaster-pa"],
    posts: ["parking-lot-line-painting-guide", "how-we-re-striped-a-26-space-commercial-lot-in-lancaster-pa-and-why-the-details-matter", "parking-lot-restriping", "parking-lot-striping-cost"],
    schemaType: "Parking lot striping",
  },
  {
    slug: "ada-parking-lot-striping-lancaster-pa",
    name: "ADA Parking Markings",
    group: "striping",
    short: "Accessible stalls, access aisles and the symbol of access, sized and counted to the 2010 ADA Standards.",
    metaTitle: "ADA Parking Lot Striping in Lancaster, PA | Accessible Stalls",
    metaDescription:
      "ADA parking striping in Lancaster, PA: accessible stalls, van spaces, access aisles and symbols done to the 2010 ADA Standards. Free estimates, 717-808-1600.",
    h1: "ADA parking lot striping in Lancaster, PA",
    kicker: "Accessible parking",
    lead: "Correct counts, correct widths, and markings that do not wear away in two winters. We stripe accessible stalls, van spaces and access aisles for commercial properties in Lancaster County.",
    hero: "ada-stall-white-outline-brick-building",
    icon: "ada",
    gallery: ["ada-blue-symbol-night-striping", "night-lot-blue-ada-hatching", "church-lot-ada-spaces-wide", "ada-stall-white-hatching-wood-deck", "shopping-lot-ada-hatching-night", "loading-zone-stencil-striping"],
    intro: [
      "Accessible parking is one of the most common places a business gets caught out. The stall might be the right size but missing an access aisle, or the aisle might be too narrow for a van lift, or there may not be enough stalls for the size of the lot. These are measurement problems, and they are easy to fix once someone measures.",
      "Under the 2010 ADA Standards, the number of accessible stalls depends on the total number of stalls in the lot. A lot with 1 to 25 stalls needs one accessible stall. 26 to 50 needs two. 51 to 75 needs three, and the count keeps rising from there. At least one in every six accessible stalls has to be van accessible, which means a wider stall or a wider access aisle. We count your lot, compare it against the table, and tell you what is required.",
      "On the pavement, we paint the stall outline, the access aisle with diagonal hatching so nobody parks in it, and the symbol of access. The federal standard requires a sign at each accessible stall, mounted at the proper height. Many municipalities and insurers also expect the painted symbol, and it is what drivers actually look for, so we recommend it.",
    ],
    includes: [
      { t: "Stall count check", d: "We count your total stalls and tell you how many accessible and van accessible stalls are required." },
      { t: "Correct dimensions", d: "Car stalls at 96 inches wide with a 60 inch aisle. Van stalls at 132 inches with a 60 inch aisle, or 96 inches with a 96 inch aisle." },
      { t: "Access aisle hatching", d: "Diagonal striping that discourages parking in the aisle, kept clear of the accessible route." },
      { t: "Symbol of access", d: "The painted wheelchair symbol, centered in the stall, in blue and white or the color your property uses." },
      { t: "Curb ramp alignment", d: "We flag stalls that do not line up with a ramp, so the accessible route actually works." },
      { t: "Restoration", d: "Worn or missing ADA markings re-done to the same standard, not just touched up." },
    ],
    signs: {
      title: "Signs your ADA markings need work",
      items: [
        "The stall outline or hatching is faded, or the symbol is gone.",
        "You have more stalls than before and never added accessible ones.",
        "Access aisles are not marked, or are painted as a solid block that gets parked on.",
        "A customer, tenant or inspector has raised a complaint.",
        "You are buying, selling or leasing the property.",
        "The accessible stall is far from the entrance, behind other stalls.",
      ],
    },
    process: [
      { t: "Count and measure", d: "Total stalls, existing accessible stalls, aisle widths and the route to the entrance." },
      { t: "Written plan", d: "A clear list of what is required, what is recommended, and the price for each." },
      { t: "Layout on the pavement", d: "Chalk lines for stalls, aisles and symbols so you can see the result before paint." },
      { t: "Paint and verify", d: "Stalls, hatching and symbols painted, then measured again against the plan." },
    ],
    faqs: [
      { q: "How many ADA parking spaces does my lot need?", a: "It depends on the total number of stalls. 1 to 25 stalls needs one. 26 to 50 needs two. 51 to 75 needs three. 76 to 100 needs four. Larger lots follow the 2010 ADA Standards table, and we will count yours." },
      { q: "What is a van accessible stall?", a: "At least one of every six accessible stalls must be van accessible. That means a 132 inch wide stall with a 60 inch access aisle, or a 96 inch stall with a 96 inch aisle, plus signage that says van accessible." },
      { q: "Do I need to paint the wheelchair symbol on the pavement?", a: "The federal standard requires a sign. The painted symbol is not always required by the standard itself, but many local codes and insurers expect it, and it is what drivers look for. We recommend it." },
      { q: "Why is there diagonal hatching beside the stall?", a: "That is the access aisle. It has to stay clear so a wheelchair or van lift can deploy. The hatching discourages people from parking in it." },
      { q: "Can you fix my signs too?", a: "We handle pavement markings. We will tell you the sign height and wording that is required, and we can coordinate with a sign installer." },
    ],
    related: ["parking-lot-striping-lancaster-pa", "fire-lane-marking-lancaster-pa", "line-striping-service-lancaster-pa"],
    posts: ["ada-parking-compliance-pennsylvania", "ada-parking-spaces-loading-zone-striping-for-a-commercial-retail-building-in-lancaster-county-pa"],
    schemaType: "ADA parking lot striping",
  },
  {
    slug: "fire-lane-marking-lancaster-pa",
    name: "Fire Lane Marking",
    group: "striping",
    short: "Painted curbs, stenciled NO PARKING FIRE LANE wording and loading zones that meet local fire official requirements.",
    metaTitle: "Fire Lane & Curb Painting in Lancaster, PA | Lines & Asphalt",
    metaDescription:
      "Fire lane painting and stenciling in Lancaster County, PA. Painted curbs, NO PARKING lettering and loading zone markings. Free estimates, 717-808-1600.",
    h1: "Fire lane marking and curb painting in Lancaster, PA",
    kicker: "Fire lanes and curbs",
    lead: "A fire lane only works if drivers can see it and respect it. We paint curbs and stencil lettering so your fire lanes, loading zones and no parking areas are unmistakable.",
    hero: "yellow-orange-curb-lines-lot",
    icon: "fire-lane",
    gallery: ["rear-lot-stencils-yellow-curb", "rear-lot-fresh-stall-lines", "no-parking-stencil-white-box", "loading-zone-stencil-striping", "ada-access-aisle-yellow-striping", "retail-lot-yellow-stalls-ada-curb"],
    intro: [
      "Fire lanes are decided by your municipality and fire official, not by the contractor. The township or borough where your property sits decides where the lane runs, how it is marked, and what the wording must be. Some want red curbs. Some want yellow. Some want stenciled lettering at a set spacing along the curb or pavement. That is why we start with your fire official's requirements before we pick a color.",
      "Once we know the rule, painting is straightforward. We clean the curb, mask it, and apply paint that is designed for curbs and pavement. We stencil NO PARKING FIRE LANE wording with consistent letter height and spacing. We also paint loading zones, no parking areas around hydrants, and hatched areas that need to be kept clear.",
      "If the lane has never been marked, we can help you work out where it makes sense based on the building layout and how apparatus would reach the building, then confirm with the township before painting.",
    ],
    includes: [
      { t: "Curb painting", d: "Red, yellow or the color your municipality requires, over a cleaned and masked curb." },
      { t: "Stenciled lettering", d: "FIRE LANE, NO PARKING and custom wording at consistent spacing and letter height." },
      { t: "Hydrant and riser clearances", d: "Marked areas around hydrants and fire department connections that need to stay open." },
      { t: "Loading zones", d: "Hatched zones and stenciled wording for deliveries and pickups." },
      { t: "Existing lane refresh", d: "Worn lettering and faded curbs brought back to a clear, readable finish." },
      { t: "Layout help", d: "A walk of the property to line up markings with what your fire official expects." },
    ],
    signs: {
      title: "When a fire lane needs attention",
      items: [
        "The curb paint has faded to a dull pink or orange.",
        "Lettering is partly worn so the wording can no longer be read.",
        "People park in the lane because it does not look like a lane.",
        "A fire inspection or insurance review asked for clearer marking.",
        "The lane runs along new construction, a new entrance or a changed layout.",
        "You are not sure where the lane is supposed to be.",
      ],
    },
    process: [
      { t: "Confirm the rule", d: "We check what your township or fire official expects for color, wording and spacing." },
      { t: "Clean and mask", d: "Curbs are cleaned and edges are masked for sharp lines." },
      { t: "Paint and stencil", d: "Curb paint goes on first, then stenciled wording at the agreed spacing." },
      { t: "Walk and cone", d: "A final walk checks every stencil. Cones stay until the paint is dry." },
    ],
    faqs: [
      { q: "Who decides where my fire lane goes?", a: "Your municipality and fire official. We paint to their requirements, and we can help you prepare the layout to take to them." },
      { q: "What color should a fire lane curb be?", a: "Red is common, but some municipalities use yellow or have their own rules. We check before we paint." },
      { q: "How long does curb paint last?", a: "With normal traffic and plowing, expect two to three years before it needs refreshing. Salt and snow removal wear paint faster along curbs." },
      { q: "Do you do the signs too?", a: "We handle painted curbs and stenciling. Signs are a separate trade, and we can coordinate." },
      { q: "Can you paint fire lanes at night?", a: "Yes. Many commercial properties prefer evenings or weekends so the lane is not blocked during business hours." },
    ],
    related: ["parking-lot-striping-lancaster-pa", "ada-parking-lot-striping-lancaster-pa", "line-striping-service-lancaster-pa"],
    posts: ["fire-lane-marking-pennsylvania", "parking-lot-striping-mistakes", "how-we-stripe-a-parking-lot"],
    schemaType: "Fire lane marking",
  },
  {
    slug: "warehouse-floor-line-marking-lancaster-pa",
    name: "Warehouse Floor Marking",
    group: "striping",
    short: "Aisle lines, forklift lanes, pedestrian paths and work zones on warehouse and industrial floors.",
    metaTitle: "Warehouse Floor Striping & Line Marking in Lancaster County",
    metaDescription:
      "Warehouse and industrial floor line marking in Lancaster County, PA. Aisle lines, forklift lanes, walkways and zones that stay sharp. Free estimates, 717-808-1600.",
    h1: "Warehouse floor striping and line marking in Lancaster County",
    kicker: "Industrial floors",
    lead: "Clear aisles and marked work zones make a warehouse safer and faster to work in. We mark concrete and coated floors with crisp lines that hold up to forklifts and foot traffic.",
    hero: "warehouse-floor-line-marking-yellow-red",
    icon: "striper-solid",
    gallery: ["warehouse-floor-lane-layout", "warehouse-floor-line-marking-dock-doors", "warehouse-red-yellow-lines-close", "warehouse-yellow-lines-lit-bay", "loading-dock-lot-asphalt"],
    intro: [
      "A marked floor is a safety tool and a productivity tool. Lines show where forklifts run, where people walk, where pallets are staged, and where nothing is allowed to sit. OSHA expects permanent aisles and passageways to be appropriately marked. Beyond compliance, a well marked floor means fewer near misses and faster picks.",
      "We start by walking the floor with whoever runs the space. We talk through traffic patterns, dock door locations, staging areas, fire equipment and electrical panels. Then we lay out the lines in chalk so everyone can see the plan before paint goes down, and adjust anything that does not work.",
      "Color is part of the system. Yellow is commonly used for aisles and work zones, red for fire equipment and no go areas, white for storage, and blue or green for special areas. We follow your existing color code, or help you set one if you do not have one.",
    ],
    includes: [
      { t: "Aisle and lane lines", d: "Forklift lanes, pedestrian walkways, and cross aisles marked at consistent widths." },
      { t: "Work cells and staging", d: "Boxes, corners and borders for staging, workstations and storage." },
      { t: "Fire equipment clearances", d: "Marked areas around extinguishers, panels and exits that must stay clear." },
      { t: "Dock door markings", d: "Lines and zones in front of dock doors and along the dock apron." },
      { t: "Color coding", d: "Yellow, red, white and other colors applied to your system." },
      { t: "Surface prep", d: "Cleaning and, where needed, light abrasion so paint bonds to the floor." },
    ],
    signs: {
      title: "When to mark or re-mark your floor",
      items: [
        "Lines are worn off in the forklift paths.",
        "Staging areas keep creeping into the aisles.",
        "You have changed your layout and the old lines are misleading.",
        "A new tenant moves in and needs its own zones.",
        "A safety audit or insurance inspection asked for clearer markings.",
        "People and forklifts share space with no clear separation.",
      ],
    },
    process: [
      { t: "Walk the floor", d: "We talk through traffic, equipment and the way work flows through the space." },
      { t: "Prep", d: "The floor is swept and cleaned, and any oil or residue is removed so paint bonds." },
      { t: "Chalk layout", d: "Lines are chalked so you can approve the plan before painting." },
      { t: "Paint and cure", d: "Lines are painted with sharp edges and clean corners, then cured before traffic returns." },
    ],
    faqs: [
      { q: "How long does it take to mark a warehouse floor?", a: "A small bay can be done in a day. Larger floors take longer, and we can work in sections to keep operations running. The time depends on the amount of line and the prep." },
      { q: "Will the paint hold up to forklifts?", a: "Properly prepped and cured paint holds up well in normal use, but high traffic lanes will wear first. We tell you where to expect touch ups." },
      { q: "Can you work on weekends or overnight?", a: "Yes. Many industrial clients prefer weekends or overnight so floors are not blocked during shifts." },
      { q: "Do you follow a standard color code?", a: "We follow your existing system. If you do not have one, we can help you set up a simple one that works for your team." },
      { q: "Do you also stripe the outdoor lot?", a: "Yes. We handle the lot, loading zones and dock aprons too, so you can have one crew for the whole property." },
    ],
    related: ["line-striping-service-lancaster-pa", "parking-lot-striping-lancaster-pa", "fire-lane-marking-lancaster-pa"],
    posts: ["warehouse-floor-line-marking-guide", "how-we-stripe-a-parking-lot"],
    schemaType: "Warehouse floor marking",
  },
  {
    slug: "sealcoating-lancaster-pa",
    name: "Sealcoating",
    group: "protection",
    short: "Commercial lot and residential sealcoating that protects asphalt from water, sun, salt and oil.",
    metaTitle: "Sealcoating & Asphalt Sealing in Lancaster, PA | Lines & Asphalt",
    metaDescription:
      "Sealcoating and asphalt sealing in Lancaster, PA: seal coating for driveways and parking lot sealing for businesses. Two coats, proper prep. Free estimates.",
    h1: "Sealcoating and asphalt sealing in Lancaster, PA",
    kicker: "Protect the pavement",
    lead: "Sealcoating is sunscreen for asphalt. It slows oxidation, keeps water out, and brings back the black surface. We do it in two coats, with proper prep, and we tell you when it is not the right move.",
    hero: "driveway-sealcoat-orange-cones",
    icon: "sealing",
    gallery: ["driveway-sealcoat-wide-apron", "driveway-sealcoat-caution-tape", "driveway-sealcoat-glossy-wet", "driveway-sealcoat-curved-apron", "driveway-sealcoat-stamped-walkway", "driveway-sealcoat-garden-edge"],
    intro: [
      "Sealcoating, also called asphalt sealing or seal coating, protects driveways and parking lots alike. Asphalt is made of stone held together by a petroleum binder. Over time the sun dries out that binder, rain and snow work their way into the surface, and salt and oil attack what is left. Sealcoating puts a thin protective layer on top, so the pavement does not have to take all of that directly.",
      "A good sealcoat job is mostly preparation. We blow the surface clean, scrape out the vegetation along the edges, treat oil spots with primer, and fill the cracks with hot rubber before anything is sprayed. Then we cut the edges in by hand with a brush so sealer stays where it belongs, and apply two coats instead of one thick one.",
      "We also tell people no. If your asphalt is under a year old, it needs to cure before it is sealed. If it is crumbling from underneath, sealer will not fix it, and we will explain the better options. Sealcoating works when it goes on pavement that is still in decent shape.",
    ],
    includes: [
      { t: "Surface cleaning", d: "Blowing, scraping and spot cleaning so the sealer can bond to real asphalt." },
      { t: "Oil spot priming", d: "Oil spots treated with primer so the sealer does not peel off them." },
      { t: "Crack filling", d: "Cracks filled with hot rubber before sealing, because sealer alone does not fill them." },
      { t: "Hand-cut edges", d: "Brush work along garages, sidewalks and lawns for clean lines." },
      { t: "Two coats", d: "Water-based emulsion with sand for traction, applied in two even coats." },
      { t: "Cure and cone", d: "Cones and tape to keep traffic off, with clear instructions on when you can drive on it." },
    ],
    signs: {
      title: "When your driveway or parking lot is ready for sealing",
      items: [
        "The surface has turned gray and the stones are starting to show.",
        "Hairline cracks are appearing but the surface is still solid.",
        "The asphalt is more than a year old.",
        "Oil and salt stains have built up in the traffic lanes.",
        "It has been three to four years since the last coat.",
        "You plan to re-stripe a lot and want it to look right.",
      ],
    },
    process: [
      { t: "Inspect", d: "We walk the surface and decide whether sealcoating is the right call." },
      { t: "Prep", d: "Clean, scrape, prime oil spots, fill cracks." },
      { t: "Edge and coat", d: "Hand-cut the edges, then apply two coats." },
      { t: "Cure", d: "Keep traffic off for 24 to 48 hours, depending on weather." },
    ],
    faqs: [
      { q: "How is sealcoating priced?", a: "By size and condition. Driveways are quoted from a quick look or a few photos; commercial lots are measured on a site visit. You always get a free written price before we start." },
      { q: "How often should I sealcoat?", a: "Every three to four years for most driveways. Busy commercial lots often need it every two to three years." },
      { q: "How long before I can drive on it?", a: "Plan on 24 to 48 hours, depending on temperature and humidity. We give you a clear time and leave cones or tape in place." },
      { q: "Can you sealcoat new asphalt?", a: "Not right away. New asphalt needs six to twelve months to cure before it is sealed. Sealing too early traps oils and the coating can fail." },
      { q: "What if it rains on my scheduled day?", a: "We reschedule. Sealer needs a dry surface and a dry cure window." },
      { q: "Does sealcoating fix cracks?", a: "No. Cracks need to be filled with hot rubber first. Sealcoating protects the pavement around them." },
    ],
    related: ["driveway-sealcoating-lancaster-pa", "crack-filling-lancaster-pa", "parking-lot-striping-lancaster-pa", "parking-lot-maintenance-lancaster-pa"],
    posts: ["driveway-sealing-vs-sealcoating", "what-is-sealcoating-and-why-does-it-matter", "best-time-to-sealcoat-pennsylvania", "sealcoating-cost-lancaster-pa", "asphalt-sealcoating-process-step-by-step"],
    schemaType: "Asphalt sealcoating",
  },
  {
    slug: "driveway-sealcoating-lancaster-pa",
    name: "Driveway Sealing & Sealcoating",
    group: "protection",
    short: "Residential driveway sealcoating with crack filling, hand-cut edges and two coats.",
    metaTitle: "Driveway Sealing & Sealcoating in Lancaster, PA | Lines & Asphalt",
    metaDescription:
      "Driveway sealing and sealcoating in Lancaster County, PA: blacktop seal coating with crack filling, two coats and hand-cut edges. Free estimates, 717-808-1600.",
    h1: "Driveway sealing and sealcoating in Lancaster County",
    kicker: "For homeowners",
    lead: "A sealed driveway looks sharp and lasts years longer. We clean it, fill the cracks, cut the edges by hand and apply two coats. Most driveways are done in a single day.",
    hero: "driveway-sealcoat-fall-tree",
    icon: "coating",
    gallery: ["driveway-sealcoat-autumn-garage", "driveway-sealcoat-small-home", "driveway-sealcoat-long-ranch", "driveway-sealcoat-sloped-cape", "driveway-sealcoat-grass-edge", "driveway-sealcoat-curved-apron", "driveway-sealcoat-orange-cones", "driveway-sealcoat-long-drive"],
    intro: [
      "Driveway sealing, sealcoating, seal coating, blacktop sealing: people use all four names for the same job, a protective coat over an asphalt driveway. Your driveway takes more abuse than most things around your house. It sits in full sun, holds snow and salt all winter, and carries cars that drip oil and fluids. By year three or four, a driveway that started out black is usually gray, dry and a little rough.",
      "Sealcoating is the cheapest way to extend the life of a driveway. It is not a miracle and it does not repair damage, but it slows the process that creates damage. Homeowners who seal on a regular schedule often get many more years before they have to think about repaving, and a sealed driveway looks sharp from the street.",
      "Our driveway jobs are done in a day. We arrive in the morning, prep and fill cracks, cut the edges by hand, spray two coats, and leave cones and tape in place. You walk the driveway with us at the end, and we tell you exactly when it will be ready for cars.",
    ],
    includes: [
      { t: "Clean and prep", d: "Blow off dirt and debris, remove weeds from edges, treat oil spots with primer." },
      { t: "Crack filling", d: "Hot rubber crack filler on cracks that need it, where the budget allows." },
      { t: "Brush edges", d: "Edges cut in by hand so nothing lands on your lawn, siding or garage door." },
      { t: "Two coats", d: "Two even coats of sealer with sand for traction." },
      { t: "Cure instructions", d: "A clear time for when you can walk, and when you can drive." },
      { t: "Clean-up", d: "We leave the site tidy and remove everything we brought." },
    ],
    signs: {
      title: "Is it time to seal your driveway?",
      items: [
        "The color is gray instead of black.",
        "Loose stones show up at the edges of the driveway.",
        "Hairline cracks are starting to form.",
        "Your last seal was three or four years ago.",
        "The driveway is more than a year old.",
        "You want curb appeal before a sale or a party.",
      ],
    },
    process: [
      { t: "Estimate", d: "Free estimate, usually from a quick look or a few photos, and a written price." },
      { t: "Prep day", d: "Clean, scrape, prime oil spots, fill cracks." },
      { t: "Coats", d: "Two coats applied with a spray wand and squeegee for even coverage." },
      { t: "Cure", d: "Stay off for 24 to 48 hours. We tell you the exact time." },
    ],
    faqs: [
      { q: "Is driveway sealing the same as sealcoating?", a: "Yes. Driveway sealing, sealcoating, seal coating and blacktop sealing all describe the same work: cleaning the asphalt, filling cracks and applying a protective sealer. The name changes from person to person, the job does not." },
      { q: "How do I get a price for my driveway?", a: "Send a few photos or ask for a visit. We look at the size and condition and give you a free written price. Large driveways and ones that need crack repair take more time and material." },
      { q: "Do I need to be home?", a: "Not during the work, but we want to do a walk through with you at the end. We also need cars out of the driveway." },
      { q: "How long does it last?", a: "Three to four years on a typical residential driveway. Sun and traffic wear it down gradually." },
      { q: "Can you seal my driveway after cracks are filled?", a: "Yes, and that is the right order. Crack filling comes first, then sealer on top." },
      { q: "Will sealer stain my walkway or garage door?", a: "We cut the edges in by hand and protect adjoining surfaces. Walk the edges with us before we start and we will point out anything that needs special care." },
    ],
    related: ["sealcoating-lancaster-pa", "crack-filling-lancaster-pa", "pothole-repair-lancaster-pa"],
    posts: ["driveway-sealing-vs-sealcoating", "how-to-seal-coat-a-driveway", "sealcoating-cost-lancaster-pa", "top-5-reasons-to-sealcoat-your-driveway", "sealcoating-myths-lancaster"],
    schemaType: "Driveway sealcoating",
  },
  {
    slug: "crack-filling-lancaster-pa",
    name: "Crack Filling & Sealing",
    group: "protection",
    short: "Hot rubberized crack sealant, applied to clean, dry cracks, so water stays out all winter.",
    metaTitle: "Asphalt Crack Filling & Crack Sealing in Lancaster, PA",
    metaDescription:
      "Asphalt crack filling, crack sealing and driveway crack repair in Lancaster County, PA. Hot pour rubber that stays flexible all winter. Free estimates.",
    h1: "Asphalt crack filling and crack sealing in Lancaster, PA",
    kicker: "Seal the cracks",
    lead: "Water gets into small cracks, freezes, and turns them into potholes. We heat rubberized sealant to about 400 degrees and fill cracks the right way, so they stay filled through a Pennsylvania winter.",
    hero: "hot-pour-crack-sealing-melter",
    icon: "crack",
    gallery: ["hot-pour-crack-fill-lot-cracks", "hot-pour-crack-sealing-crew", "crack-filled-commercial-drive", "retail-lot-angled-yellow-stripes", "driveway-sealcoat-long-evergreens"],
    intro: [
      "A crack in asphalt is not the problem. The water that gets in through the crack is. Once it is under the surface, it softens the base. When temperatures drop, it freezes and expands, pushing the pavement apart. When it thaws, it leaves a void. Repeat that a few dozen times in a Lancaster County winter and you have a pothole.",
      "Hot pour crack sealing stops that cycle. We clean the crack, heat a rubberized sealant in a melter, and fill the crack from the bottom up. The rubber stays flexible, so it moves with the pavement as temperatures swing. That is what makes it different from the cold-pour bottle you buy at the hardware store.",
      "Fall is the best season for crack filling in this area. Cracks are at their widest in cold weather, which means they take more material, and filling them before winter keeps water from doing damage. We also fill before sealcoating, because sealer by itself does not fill a crack.",
    ],
    includes: [
      { t: "Crack assessment", d: "We walk the pavement and decide which cracks need filling and which are structural and need other repair." },
      { t: "Cleaning", d: "Dirt, debris and vegetation blown or scraped out so the rubber can bond." },
      { t: "Hot rubber fill", d: "Rubberized sealant heated to about 400 degrees F and applied from the bottom up." },
      { t: "Strike-off", d: "Material squeegeed flush so it does not create a bump for cars or plows." },
      { t: "Cure and reopen", d: "A short cure time, then you can drive on it." },
      { t: "Pairing with sealcoat", d: "We schedule crack filling and sealcoating together when it makes sense." },
    ],
    signs: {
      title: "When to fill or seal cracks in your driveway or lot",
      items: [
        "Cracks wider than a credit card edge are open to the sky.",
        "You can see weeds growing in the cracks.",
        "Water pools along a crack after rain.",
        "It is fall and you want to protect the pavement before winter.",
        "You are planning to sealcoat.",
        "Last year's cracks are wider this year.",
      ],
    },
    process: [
      { t: "Assess", d: "We map the cracks and decide what can be sealed." },
      { t: "Clean", d: "Blow out debris and clear vegetation." },
      { t: "Heat and fill", d: "Heat the rubber and fill the cracks from the bottom up." },
      { t: "Finish", d: "Squeegee flush and let it cure before traffic returns." },
    ],
    faqs: [
      { q: "What is the difference between crack filling and crack sealing?", a: "People use the words interchangeably. Strictly, crack sealing uses a flexible material placed into cracks that move with temperature, and crack filling is for cracks that move less. We use hot pour rubberized sealant for both on driveways and lots, because it stays flexible through Pennsylvania winters." },
      { q: "What is the difference between hot pour and cold pour crack filler?", a: "Hot pour is a rubberized material heated to about 400 degrees. It bonds to the sides of the crack and stays flexible in the cold. Cold pour is easier to apply but typically doesn't last as long in our climate." },
      { q: "How is crack filling priced?", a: "By the total length of cracks and how much cleaning they need. Commercial lots are measured on site. Quotes are free and in writing." },
      { q: "Can you fill cracks in winter?", a: "Cracks must be clean and dry. Light work is possible on dry days, but the best window is fall, before winter sets in." },
      { q: "How long does it last?", a: "With proper prep, several years. It eventually wears and can be redone." },
      { q: "Should I fill cracks before sealcoating?", a: "Yes. Sealcoating by itself does not fill cracks. Fill first, then seal." },
    ],
    related: ["sealcoating-lancaster-pa", "pothole-repair-lancaster-pa", "driveway-sealcoating-lancaster-pa", "parking-lot-maintenance-lancaster-pa"],
    posts: ["asphalt-driveway-crack-repair", "hot-pour-crack-sealing-process", "crack-filling-cost-lancaster-county", "hot-pour-vs-cold-pour-crack-filler", "crack-filling-before-winter-lancaster"],
    schemaType: "Crack filling",
  },
  {
    slug: "pothole-repair-lancaster-pa",
    name: "Asphalt & Pothole Repair",
    group: "repair",
    short: "Square-cut, base-checked, hot mix repairs that stay put, plus temporary patches in winter.",
    metaTitle: "Asphalt Repair & Pothole Patching in Lancaster, PA",
    metaDescription:
      "Asphalt repair, pothole patching and driveway repair in Lancaster County, PA. Square-cut edges, base repair, hot mix compacted in lifts. Free estimates.",
    h1: "Asphalt repair and pothole patching in Lancaster, PA",
    kicker: "Fix it right",
    lead: "A pothole you fix with a shovelful of loose patch comes back by spring. We cut the edges square, repair the base, and place hot mix in compacted layers, so the repair becomes part of the pavement.",
    hero: "private-lane-fresh-asphalt",
    icon: "repair",
    gallery: ["driveway-resurfaced-edge-gravel", "driveway-fresh-asphalt-garage", "driveway-fresh-asphalt-leaves", "private-drive-fresh-asphalt-house", "loading-dock-lot-asphalt"],
    intro: [
      "Most asphalt repair on driveways and parking lots comes down to the same problem: a spot where the surface has failed. Potholes are what happens when water, freezing temperatures and traffic find a weak spot. The pavement cracks, water gets in, the base softens, and the surface collapses. Filling just the hole does not fix any of that.",
      "A repair that lasts starts by cutting the hole back to sound pavement with square, vertical edges. We remove the loose material, check and rebuild the base if it has failed, brush a tack coat on the sides and bottom so new asphalt bonds, then place hot mix in layers. Each layer is compacted before the next goes on. The patch is finished flush and sealed at the seam so water cannot get back in.",
      "In the coldest months, hot mix is generally not available. We can place cold patch as a temporary fix to keep a hole from getting worse, and return in spring for a permanent repair. We will tell you honestly when a patch is the wrong answer and the better move is a larger repair or an overlay.",
    ],
    includes: [
      { t: "Square cutting", d: "Edges cut back to healthy pavement so the patch has something solid to bond to." },
      { t: "Base repair", d: "Soft or washed-out base removed and rebuilt before new asphalt goes in." },
      { t: "Tack coat", d: "A thin bonding layer on the sides and bottom of the hole." },
      { t: "Hot mix in lifts", d: "Asphalt placed in layers, compacted as it goes." },
      { t: "Seam sealing", d: "The edge of the patch sealed so water cannot work back in." },
      { t: "Winter cold patch", d: "A temporary fix in cold weather, with a plan for a permanent repair in spring." },
    ],
    signs: {
      title: "Patch it, repair it, or plan a bigger fix",
      items: [
        "One to a few isolated holes with solid pavement around them: patching works well.",
        "Holes that keep returning in the same spots: the base underneath needs work.",
        "Alligator cracking across a wide area: patches will not hold, ask us about larger options.",
        "Edges crumbling around the hole: it needs to be cut back farther.",
        "Standing water in a low spot: drainage needs to be part of the repair.",
        "A hole in a lot where customers or vehicles drive: do not wait, it is a liability.",
      ],
    },
    process: [
      { t: "Inspect", d: "We look at the hole, the surrounding pavement and the drainage." },
      { t: "Cut and clean", d: "Cut the edges square, remove loose material and debris." },
      { t: "Base and tack", d: "Repair the base if needed and apply tack coat." },
      { t: "Fill and compact", d: "Hot mix in lifts, compacted, finished flush and sealed." },
    ],
    faqs: [
      { q: "Do you repair asphalt driveways, or just parking lots?", a: "Both. Driveway repair is a big part of our work: potholes near the garage, crumbling edges, soft spots and sunken areas. The method is the same as on a parking lot, cut back to sound asphalt, fix the base and patch with hot mix." },
      { q: "How is pothole repair priced?", a: "By the number of holes, their depth and the condition of the base underneath. We look at the holes and give you a free written price before any work starts." },
      { q: "Why do you cut the hole bigger?", a: "The edges of a pothole are weak. Cutting back to sound pavement gives the patch something solid to bond to." },
      { q: "What is the difference between cold patch and hot mix?", a: "Cold patch is for emergency winter repairs. Hot mix is a permanent repair and is used when temperatures allow." },
      { q: "Will the patch match my driveway?", a: "A fresh patch is black and will blend over time. Sealcoating the whole driveway makes everything uniform." },
      { q: "Can you fill the cracks around the pothole too?", a: "Yes. That is often the smart move. Fixing the cracks stops the next pothole from forming." },
    ],
    related: ["crack-filling-lancaster-pa", "sealcoating-lancaster-pa", "parking-lot-maintenance-lancaster-pa"],
    posts: ["cold-patch-vs-hot-mix-asphalt", "pothole-repair-process", "pothole-repair-cost-lancaster-pa", "why-potholes-form-freeze-thaw", "pothole-repair-vs-full-repaving-which-one-do-you-actually-need"],
    schemaType: "Pothole repair",
  },
  {
    slug: "parking-lot-maintenance-lancaster-pa",
    name: "Parking Lot Maintenance",
    group: "protection",
    short: "A simple yearly plan: fill cracks, patch holes, sealcoat and re-stripe in the right order.",
    metaTitle: "Parking Lot Maintenance in Lancaster, PA | Seal, Patch & Stripe",
    metaDescription:
      "Parking lot maintenance in Lancaster County, PA. Crack filling, pothole repair, sealcoating and striping in the right order. Free estimates, 717-808-1600.",
    h1: "Parking lot maintenance in Lancaster, PA",
    kicker: "One crew, one visit",
    lead: "A lot lasts longest when the work is done in order. Fill the cracks, patch the holes, seal the surface, then paint the lines. One crew can handle all of it.",
    hero: "retail-lot-restriped-blue-ada",
    icon: "lot",
    gallery: ["retail-lot-fresh-yellow-stripes", "hot-pour-crack-fill-lot-cracks", "church-lot-white-stalls-drain", "rear-lot-stencils-yellow-curb", "dusk-lot-stall-lines-fresh-paint"],
    intro: [
      "Most parking lot problems start small. A hairline crack, a dull patch of gray, a few faded stalls. Left alone, those become potholes, drainage problems and a lot that looks tired. The good news is that a lot is cheap to maintain compared with replacing it.",
      "The order of work matters. Cracks are filled first so water cannot get in. Potholes and failed areas are repaired next, so the surface is sound. Sealcoating goes on after that to protect the pavement. Line striping goes down last, on a sealed surface, so the paint looks sharp and lasts. Doing it out of order wastes money, which is why we like to plan a lot as a package.",
      "We can help you set up a simple schedule: filling cracks every fall, sealcoating every two to three years for busy lots, and restriping when the lines fade. For property managers with more than one site, we can stagger the work across a budget year.",
    ],
    includes: [
      { t: "Lot assessment", d: "A walk of the whole lot with a written list of what needs doing, ranked by urgency." },
      { t: "Crack filling", d: "Hot pour rubber on cracks that are open to water." },
      { t: "Pothole and base repair", d: "Failed areas cut out and rebuilt, not just topped off." },
      { t: "Sealcoating", d: "Two coats, with crews scheduled around your business hours." },
      { t: "Striping and ADA", d: "Fresh lines, ADA stalls, fire lanes and stencils to finish the job." },
      { t: "Seasonal plan", d: "A calendar that spreads the cost and keeps work in the right order." },
    ],
    signs: {
      title: "A lot that needs a plan",
      items: [
        "Several different problems at once: cracks, holes and faded lines.",
        "A lot that has not been maintained in three or more years.",
        "A property manager responsible for several sites.",
        "A tenant or insurer has asked for a maintenance record.",
        "Budget season, and you want to know what to plan for.",
        "You are about to sell or refinance and want the lot to look right.",
      ],
    },
    process: [
      { t: "Assess", d: "We walk the lot and photograph problem areas." },
      { t: "Plan", d: "You get a written plan, in order, with prices for each step." },
      { t: "Schedule", d: "We schedule around business hours and the weather." },
      { t: "Work and review", d: "We do the work and walk it with you at the end." },
    ],
    faqs: [
      { q: "What order should lot maintenance be done in?", a: "Crack filling first, then pothole and base repair, then sealcoating, then striping. Each step protects the next one." },
      { q: "How often should I maintain a parking lot?", a: "Fill cracks every year, sealcoat every two to three years for busy lots, and re-stripe every one to two years." },
      { q: "Can you work around my business hours?", a: "Yes. We schedule evenings, early mornings and weekends, and we do the work in sections if the lot needs to stay open." },
      { q: "Do you work with property managers?", a: "Yes. We handle single sites and portfolios. We can help you plan work across a budget year." },
      { q: "What if my lot is beyond maintenance?", a: "We will tell you. If the surface is failing across a large area, patching and sealing will not work, and we will explain the options." },
    ],
    related: ["crack-filling-lancaster-pa", "pothole-repair-lancaster-pa", "sealcoating-lancaster-pa", "parking-lot-striping-lancaster-pa"],
    posts: ["asphalt-driveway-maintenance-schedule", "spring-asphalt-checklist-what-to-fix-after-winter", "parking-lot-pothole-repair-business", "parking-lot-restriping"],
    schemaType: "Parking lot maintenance",
  },
];

export const bySlug = (slug: string) => services.find((s) => s.slug === slug);
