import sharp from 'sharp'; import fs from 'fs'; import path from 'path';
const LOCAL='../source-media', OLD='scripts/oldimgs';
// [file, dir, slug, category, alt]
const L=(f,s,c,a)=>[f,LOCAL,s,c,a], O=(f,s,c,a)=>[f,OLD,s,c,a];
// Batch sent by the client over WhatsApp on 2026-10-06 (no EXIF, so no dates or towns).
const W=(f,s,c,a)=>[f,LOCAL+'/2026-10-06',s,c,a];
const items=[
 W('wa01.jpeg','long-rural-driveway-sealed-lawn','sealcoating','Long rural driveway freshly sealed, curving across a wide lawn'),
 W('wa02.jpeg','long-driveway-sealcoat-tree-line','sealcoating','Long sealcoated driveway running toward a house past a tree line'),
 W('wa03.jpeg','driveway-sealcoat-concrete-walk-edge','sealcoating','Sealcoated driveway with a clean edge along a concrete walkway'),
 W('wa04.jpeg','small-lot-restripe-white-stalls-sunset','striping','Small parking lot re-striped with white stall lines at sunset'),
 W('wa05.jpeg','small-lot-white-arrows-sealed','striping','Sealed lot with new white directional arrows and stall lines'),
 W('wa06.jpeg','donation-center-lot-white-hatching','striping','White hatched zone and arrow painted in front of a donation center'),
 W('wa07.jpeg','donation-center-lot-ada-hatching','ada','Donation center lot with blue ADA stalls and white hatched no parking area'),
 W('wa08.jpeg','night-ada-stall-curb-striping','ada','Blue ADA stall with white access aisle hatching painted at night beside a curb'),
 W('wa09.jpeg','loading-area-sealcoat-green-bollards','sealcoating','Freshly sealed asphalt under a loading canopy with green bollards'),
 W('wa10.jpeg','commercial-lot-white-stalls-hatching-aerial','striping','Commercial lot re-striped with white stalls and hatching, seen from above'),
 W('wa11.jpeg','wooded-driveway-sealcoat-curve','sealcoating','Sealcoated driveway curving through a wooded yard'),
 W('wa12.jpeg','wooded-driveway-sealcoat-long','sealcoating','Long sealcoated driveway through trees and shrubs'),
 W('wa13.jpeg','brick-building-lot-yellow-stalls','striping','Parking lot behind a brick building with fresh yellow stall lines'),
 W('wa14.jpeg','school-lot-yellow-hatching-ada','ada','Yellow hatched aisle and stalls with a blue ADA stall by a brick building'),
 W('wa15.jpeg','brick-building-blue-ada-stall','ada','Blue ADA stall with the symbol of access and blue lines beside a brick building'),
 W('wa16.jpeg','driveway-sealcoat-caution-tape-farmhouse','sealcoating','Sealcoated driveway taped off for curing in front of a country home'),
 W('wa17.jpeg','long-hill-driveway-sealcoat','sealcoating','Long hillside driveway sealcoated with a crisp grass edge'),
 W('wa18.jpeg','driveway-apron-sealcoat-road-tape','sealcoating','Sealcoated driveway apron at the road, taped off while it cures'),
 W('wa19.jpeg','rural-driveway-sealcoat-tape-road','sealcoating','Rural driveway freshly sealed and taped off where it meets the road'),
 W('wa20.jpeg','wide-driveway-sealcoat-planter','sealcoating','Wide driveway sealcoated past a planter and lawn'),
 W('wa21.jpeg','driveway-sealcoat-barn-view','sealcoating','Sealcoated driveway beside a house with a barn in the background'),
 W('wa22.jpeg','yellow-house-wide-driveway-sealcoat','sealcoating','Wide sealcoated driveway in front of a yellow house with a three-car garage'),
 W('wa23.jpeg','long-driveway-sealcoat-to-house','sealcoating','Long straight driveway sealcoated up to the house'),
 W('wa24.jpeg','ranch-house-driveway-sealcoat-tape','sealcoating','Ranch house driveway freshly sealcoated and taped off at the street'),
 W('wa25.jpeg','driveway-sealcoat-evening-glow','sealcoating','Freshly sealcoated driveway in evening light'),
 W('wa26.jpeg','driveway-sealcoat-tape-two-story','sealcoating','Sealcoated driveway taped off in front of a two-story home'),
 W('wa27.jpeg','curved-driveway-sealcoat-dusk','sealcoating','Curved driveway sealcoated at dusk in a residential neighborhood'),
 L('IMG_1652.JPEG','retail-lot-yellow-stalls-ada-curb','striping','Yellow-striped parking stalls and a blue ADA curb outside a retail plaza'),
 L('IMG_1653.JPEG','retail-lot-fresh-yellow-stripes','striping','Freshly painted yellow stall lines across a large retail parking lot'),
 L('IMG_1655.JPEG','retail-lot-angled-yellow-stripes','striping','Angled yellow parking stripes laid out on a crack-filled asphalt lot'),
 L('IMG_1751.JPEG','shopping-center-yellow-hatching','striping','Yellow hatched striping and parking lines in a shopping center lot'),
 L('IMG_1754.JPEG','retail-lot-restriped-blue-ada','striping','Restriped retail parking lot with yellow lines and a blue ADA stall'),
 L('IMG_1756.JPEG','ada-access-aisle-yellow-striping','striping','Yellow ADA access aisle striping beside a brick commercial building'),
 L('IMG_1820.JPEG','white-directional-arrows-lane-line','striping','White directional arrows and a curved lane line painted on a business entrance drive'),
 L('IMG_2123.JPEG','no-parking-stencil-white-box','striping','White NO PARKING stencil inside a painted box on a small parking area'),
 L('IMG_2787.JPEG','warehouse-floor-line-marking-yellow-red','warehouse','Yellow and red safety line layout painted on a warehouse floor'),
 L('IMG_2791.JPEG','warehouse-floor-lane-layout','warehouse','Warehouse floor with yellow lane boxes and a red divider line'),
 L('IMG_2792.JPEG','warehouse-floor-line-marking-dock-doors','warehouse','Marked work zones on an industrial floor in front of dock doors'),
 L('IMG_2794.JPEG','warehouse-red-yellow-lines-close','warehouse','Close view of crisp red and yellow floor marking lines in a warehouse'),
 L('IMG_2798.JPEG','warehouse-yellow-lines-lit-bay','warehouse','Yellow floor layout lines in a lit warehouse bay'),
 L('IMG_1894.JPEG','driveway-sealcoat-orange-cones','sealcoating','Freshly sealcoated black driveway with orange cones beside a two-story home'),
 L('IMG_1895.JPEG','driveway-sealcoat-curved-apron','sealcoating','Newly sealcoated curved driveway beside a lawn and garden shed'),
 L('IMG_1913.JPEG','driveway-sealcoat-grass-edge','sealcoating','Sealcoated driveway with a clean hand-cut edge along the grass'),
 L('IMG_1918.JPEG','driveway-sealcoat-long-drive','sealcoating','Long residential driveway freshly sealcoated in black'),
 L('IMG_1964.JPEG','driveway-sealcoat-wide-apron','sealcoating','Wide sealcoated driveway apron in front of a two-car garage'),
 L('IMG_1965.JPEG','driveway-sealcoat-caution-tape','sealcoating','Sealcoated driveway with caution tape marking the curing zone'),
 L('IMG_1974.JPEG','driveway-sealcoat-stamped-walkway','sealcoating','Black sealcoated driveway next to a stamped concrete walkway'),
 L('IMG_1975.JPEG','driveway-sealcoat-sloped-cape','sealcoating','Sloped driveway sealcoated in front of a Cape Cod style home'),
 L('IMG_2132.JPEG','driveway-sealcoat-glossy-wet','sealcoating','Wet-look fresh sealcoat on a driveway in front of a brick colonial'),
 L('IMG_2134.JPEG','driveway-sealcoat-garden-edge','sealcoating','Freshly sealcoated driveway running alongside flower beds'),
 L('IMG_2158.JPEG','driveway-sealcoat-long-ranch','sealcoating','Long ranch house driveway with fresh sealcoat and caution tape'),
 L('IMG_2159.JPEG','driveway-sealcoat-long-evergreens','sealcoating','Long driveway bordered by evergreens with sealed surface cracks'),
 L('IMG_2178.JPEG','driveway-sealcoat-small-home','sealcoating','Narrow driveway at a small home sealcoated in even black'),
 L('IMG_2205.JPEG','driveway-sealcoat-fall-tree','sealcoating','Sealcoated driveway under a fall maple tree'),
 L('IMG_2211.JPEG','driveway-sealcoat-autumn-garage','sealcoating','Sharp black sealcoat in front of a garage on an autumn day'),
 L('IMG_3664.JPG','driveway-resurfaced-edge-gravel','sealcoating','Freshly laid asphalt driveway edge with gravel shoulder and caution tape'),
 L('IMG_3666.JPG','private-lane-fresh-asphalt','sealcoating','Private lane with fresh asphalt through the trees'),
 L('IMG_3670.JPG','private-drive-fresh-asphalt-house','sealcoating','New asphalt driveway leading up to a large home'),
 L('IMG_3672.JPG','driveway-fresh-asphalt-leaves','sealcoating','Fresh black asphalt apron with autumn leaves'),
 L('IMG_3673.JPG','driveway-fresh-asphalt-garage','sealcoating','Freshly finished asphalt pad in front of a double garage'),
 O('IMG_3796.jpeg','ada-stall-white-outline-brick-building','ada','ADA parking stall with white outline and access aisle hatching beside a historic building'),
 O('IMG_3811.jpeg','ada-stall-white-hatching-wood-deck','ada','White hatched ADA access aisle and symbol on a small commercial lot'),
 O('IMG_3843.jpeg','loading-zone-stencil-striping','ada','Loading zone stencil and diagonal hatching in front of a commercial entrance'),
 O('IMG_3845.jpeg','ada-blue-symbol-night-striping','ada','Blue ADA symbols and hatched access aisles painted at night'),
 O('IMG_3846.jpeg','parking-stalls-wheel-stops-white-lines','ada','White parking stalls with wheel stops beside a lawn'),
 O('IMG_4203.jpeg','night-striping-ada-stall-cones','ada','Night striping crew work on a blue ADA stall surrounded by cones'),
 O('IMG_4211.jpeg','empty-lot-night-white-stalls','ada','Large commercial lot restriped overnight with crisp white stall lines'),
 O('IMG_4212.jpeg','striper-machine-night-lot','ada','Line striping machine on a freshly marked commercial lot at night'),
 O('IMG_4216.jpeg','night-lot-blue-ada-hatching','ada','Blue ADA symbol and hatching on a lot lit by street lights'),
 O('IMG_4219.jpeg','shopping-lot-ada-hatching-night','ada','Hatched ADA access aisle in a shopping center lot at night'),
 O('IMG_4369.jpeg','dusk-lot-stall-lines-fresh-paint','ada','Fresh white stall lines on blacktop at dusk'),
 O('IMG_4407.jpeg','numbered-parking-stall-white','striping','Numbered parking stall freshly painted in white'),
 O('IMG_4424.jpeg','small-business-lot-numbered-stalls','striping','Numbered white stalls on a small business parking lot'),
 O('IMG_4427.jpeg','lot-with-ada-hatching-aerial','striping','Parking lot with ADA hatching seen from an elevated angle'),
 O('IMG_4434.jpeg','lot-arrows-white-center-line','striping','White arrows and a center line directing traffic in a parking lot'),
 O('IMG_4443.jpeg','yellow-orange-curb-lines-lot','striping','Yellow and orange line work across a wide commercial lot'),
 O('IMG_4495.jpeg','residential-lot-white-stalls','striping','White stall lines on a small residential property lot'),
 O('IMG_4623.jpeg','reserved-stencil-night','striping','RESERVED stencil on a parking stall in front of an office at night'),
 O('IMG_4743.jpeg','loading-dock-lot-asphalt','striping','Warehouse loading dock apron with sealed asphalt'),
 O('IMG_5607.jpeg','church-lot-white-stalls-drain','striping','Fresh white stall lines in a stone building lot'),
 O('IMG_5609.jpeg','church-lot-ada-spaces-wide','ada','Wide view of a lot with new white stalls and ADA spaces'),
 O('IMG_5610.jpeg','church-lot-ada-hatched-stalls','ada','ADA stalls with blue symbols and hatched aisles in a restriped lot'),
 O('IMG_5616.jpeg','restriped-lot-shadow-white-lines','striping','Restriped lot with fresh white lines and long afternoon shadows'),
 O('IMG_5617.jpeg','office-park-stall-line-fresh','striping','New white stall line next to a lawn at an office park'),
 O('IMG_3364.jpeg','order-here-stencil-drive','striping','ORDER HERE stencil and curved arrow on a drive-through lane'),
 O('IMG_3412.jpeg','rear-lot-stencils-yellow-curb','striping','Rear lot with stall lines, stencils and a yellow curb line beside a building'),
 O('IMG_3414.jpeg','rear-lot-restriped-numbered','striping','Numbered rear lot restriped with white lines and an ADA stall'),
 O('IMG_3416.jpeg','rear-lot-fresh-stall-lines','striping','Fresh stall lines and yellow curb marking on repaired asphalt'),
 O('IMG_3473.jpeg','hot-pour-crack-sealing-melter','cracks','Hot pour crack sealer filling a long crack across a parking lot'),
 O('IMG_3474.jpeg','hot-pour-crack-fill-lot-cracks','cracks','Crack sealing equipment and freshly filled cracks across a parking lot'),
 O('IMG_3475.jpeg','hot-pour-crack-sealing-crew','cracks','Crew member applying hot rubber crack sealant with a pour pot'),
 O('IMG_3476.jpeg','crack-filled-commercial-drive','cracks','Sealed cracks running along a commercial entrance drive'),
];
const out='public/img'; fs.mkdirSync(out,{recursive:true});
const manifest={};
for(const [f,dir,slug,cat,alt] of items){
  const src=path.join(dir,f); if(!fs.existsSync(src)){console.log('MISSING',src);continue;}
  const base=sharp(src,{failOn:'none'}).rotate();
  const big=await base.clone().resize({width:1600,height:1600,fit:'inside',withoutEnlargement:true}).webp({quality:78}).toFile(`${out}/${slug}.webp`);
  const sm=await base.clone().resize({width:640,height:640,fit:'inside',withoutEnlargement:true}).webp({quality:72}).toFile(`${out}/${slug}-sm.webp`);
  manifest[slug]={slug,cat,alt,w:big.width,h:big.height,sw:sm.width,sh:sm.height};
}
fs.writeFileSync('src/content/images.json',JSON.stringify(manifest,null,1));
console.log(Object.keys(manifest).length,'images');
